### ISSUE TITLE
Why are only styles removed and no scripts?

### ISSUE THREAD

**Issue by adekrijger** [senlin/classic-editor-addon#15] opened 2023-02-08 11:50 UTC
I saw that only styles are removed and I'd like to remove everything connected to blocks. Probably you have done this for a reason. Can you please share why?

**Comment by senlin** [comment] 2023-02-08 12:16
Please elaborate

possible Duplicate of #14 (or related)?

**Comment by adekrijger** [comment] 2023-02-08 13:55
Hi Pieter,

all kinds of javascript is also added by blocks if I'm not wrong?

Why are those not removed?

Met vriendelijke groet / Kind regards,

Albert de Krijger



Op 8-2-2023 om 13:16 schreef Pieter Bos:

**Comment by senlin** [comment] 2023-02-08 15:34
It would be helpful if you were able to point out **exactly** which scripts are still showing after activating the **Classic Editor +**  plugin.

**Comment by adekrijger** [comment] 2023-02-08 15:45
all in the print screen, the print screen is after activating

Met vriendelijke groet / Kind regards,

Albert de Krijger



Op 8-2-2023 om 16:34 schreef Pieter Bos:

**Comment by senlin** [comment] 2023-02-08 15:55
Ok thanks for making have another good look at things.

Turns out that the function to remove the lot needs to be called now with `enqueue_block_assets` instead of `wp_enqueue_scripts`.

just released new version, will update on WP soon too

**Comment by joldnl** [comment] 2023-02-08 16:01
@senlin I believe @adekrijger tries to explain that javascript assets for the block editor are still enqueued and loaded on both front end and back end, as opposed to the styles assets that are dequeued or deregistered in the current situation of the plugin

**Comment by senlin** [comment] 2023-02-08 16:03
Thank you @joldnl - I tried to get someone to show me concretely which scripts are being loaded. Post a screenshot so I can see please.

**Comment by senlin** [comment] 2023-02-08 18:08
closing this as there are no scripts in my opinion; feel free to re-open with screenshot of actual scripts found.

**Closed as completed by senlin** 2023-02-08 18:08 UTC

**Comment by joldnl** [comment] 2023-02-09 09:09
@senlin Sure, just a quick look at the scripts loaded for woocommerce blocks:

```
wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-blocks-registry.js
wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-blocks-middleware.js
wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-blocks-data.js
wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/blocks-checkout.js
```

**Comment by senlin** [comment] 2023-02-09 11:55
Thanks, not sure where this is a screenshot of though as it doesn't show any other information...

I would like to show you [this vanilla setup](https://sandbox-online.com/wcdev/product/plof/), so you can see that there are no scripts being loaded. The only plugins installed there are WooCommerce and the Classic Editor + plugin. It uses the default Storefront theme (which does seem to add some blocks styling).

I don't want to make this into a yes/no game, but for me to address this as an issue, you will need to help me understand it and provide as much information as possible.

**Comment by senlin** [comment] 2023-02-09 12:07
Could it perhaps be that you have a separate plugin called [WooCommerce Blocks](https://wordpress.org/plugins/woo-gutenberg-products-block/) installed?
